core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='about', view=views.about, name='about'),
]

mbta_api_playground/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('params/', include('params.urls')),
    path('queries/', include('queries.urls')),
    path('', include('core.urls')),
]

queries/urls.py
from django.urls import path
from . import views


app_name = 'queries'
urlpatterns = [
    path('create/', views.QueryCreate.as_view(), name='create'),
    path('requests/', views.RequestList.as_view(), name='request-list'),
    path('results/<int:pk>/', views.QueryResults.as_view(), name='results'),
    path('results/<int:pk>/csv/', views.results_as_csv, name='results-csv'),
    path('results/<int:pk>/report/<str:correlations>/', views.results_create_report),
    path('results/<int:pk>/dtale/', views.results_dtale, name='results-dtale'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import redirect, render


def home(request):
    return redirect('about')


def about(request):
    return render(request, 'core/about.html', context={})

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
	<h5 class="bd-title py-md-3">About</h5>
	<p>
		This is a tool for learning how to interact with the MBTA V3 API.
	</p>
	<p>
		You can build and execute complicated queries, customizing the objects, attributes, and filters.  The results are then transformed into a pandas dataframe for easy exploration.
	</p>
	<a class="btn btn-primary" href="{% url 'queries:create' %}" role="button">Go create a query</a>
	<hr>
  <h5>Resources</h5>
  <ul>
  	<li><a href="https://github.com/phillipdupuis/mbta-api-playground">Source code</a></li>
   	<li><a href="https://www.mbta.com/developers/v3-api">MBTA Developers Page</a></li>
    <li><a href="https://api-v3.mbta.com/docs/swagger/index.html">MBTA V3 API Documentation</a></li>
    <li><a href="https://developers.google.com/transit/gtfs/">GTFS Overview</a></li>
   </ul>
</div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Phillip Dupuis">
  <title>MBTA API Playground</title>
  <link rel="canonical" href="https://www.mbta-api-playground.com/">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/base.css' %}">
  {% block extrastyles %}
  {% endblock extrastyles %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'home' %}">MBTA API Playground</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarActionList" aria-controls="navbarActionList" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarActionList">
      <ul class="navbar-nav mr-auto">
        {% with current_page=request.resolver_match.url_name %}
          <li class="nav-item {% if current_page == 'about' %}active{% endif %}">
            <a class="nav-link" href="{% url 'about' %}">About
              <span class="sr-only">{% if current_page == 'about' %}(current){% endif %}</span>
            </a>
          </li>
          <li class="nav-item {% if current_page == 'create' %}active{% endif %}">
            <a class="nav-link" href="{% url 'queries:create' %}">Create
              <span class="sr-only">{% if current_page == 'create' %}(current){% endif %}</span>
            </a>
          </li>
          <li class="nav-item {% if current_page == 'request-list' %}active{% endif %}">
            <a class="nav-link" href="{% url 'queries:request-list' %}">Recent
              <span class="sr-only">{% if current_page == 'request-list' %}(current){% endif %}</span>
            </a>
          </li>
        {% endwith %}
      </ul>
      <a target="_blank" href="https://github.com/phillipdupuis/mbta-api-playground" data-toggle="tooltip" data-placement="left" title="Github">
        <img src="{% static 'core/images/mark-github.svg' %}" alt="github" class="github-icon d-none d-sm-none d-md-block" height="24" width="24">
      </a>
    </div>
  </nav>
  <div class="container-fluid">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- JavaScript -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% block extrascripts %}
  {% endblock extrascripts %}
</body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
	<p>Hello this is the home page!</p>
{% endblock %}

core/templates/core/loading_screen.html
<div class="modal" tabindex="-1" role="dialog" id="modal-loading-screen" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content justify-content-center align-items-center">
      <div id="loading-screen-message">Loading...</div>
      <div class="d-inline align-items-center">
        <div class="spinner-grow m-2"></div>
        <div class="spinner-grow m-2"></div>
        <div class="spinner-grow m-2"></div>
      </div>
    </div>
  </div>
</div>

core/templates/core/modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><!-- Insert title --></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="max-height:70vh;overflow-y:auto;"><!-- Insert body --></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="modal-save-btn">Save</button>
      </div>
    </div>
  </div>
</div>
<!-- <script type="javascript">
    $('#modal').on('shown', function () {
        $('.modal-body').scrollTop(0);
    });
</script>-->