core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='about', view=views.about, name='about'),
]

mbta_api_playground/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('params/', include('params.urls')),
    path('queries/', include('queries.urls')),
    path('', include('core.urls')),
]

queries/urls.py
from django.urls import path
from . import views


app_name = 'queries'
urlpatterns = [
    path('create/', views.QueryCreate.as_view(), name='create'),
    path('requests/', views.RequestList.as_view(), name='request-list'),
    path('results/<int:pk>/', views.QueryResults.as_view(), name='results'),
    path('results/<int:pk>/csv/', views.results_as_csv, name='results-csv'),
    path('results/<int:pk>/report/<str:correlations>/', views.results_create_report),
    path('results/<int:pk>/dtale/', views.results_dtale, name='results-dtale'),
]

queries/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.formats import date_format
from typing import List
from collections import OrderedDict
import json
import requests
import pandas as pd
import pandas_profiling
import matplotlib
matplotlib.use('Agg')
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.embed import json_item
from bokeh.tile_providers import get_provider, Vendors
from pyproj import Proj, transform
from params.models import MbtaObject, MbtaInclude, MbtaAttribute, MbtaFilter


class Query(models.Model):
    """
    Defines the parameters for a query to the MBTA API.
    Allows the user to define a primary resource, included resources, attributes,
    and filters.
    """
    primary_object = models.ForeignKey(
        MbtaObject,
        on_delete=models.CASCADE,
        verbose_name='Object',
        related_name='queries',
    )
    includes = models.ManyToManyField(
        MbtaInclude,
        verbose_name='Include',
        related_name='included_in_queries',
        blank=True,
    )
    attributes = models.ManyToManyField(
        MbtaAttribute,
        verbose_name='Attributes',
        related_name='included_in_queries',
    )
    url = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.url

    def all_objects(self) -> List[MbtaObject]:
        objects = [self.primary_object]
        for include in self.includes.filter(associated_object__isnull=False):
            objects.append(include.associated_object)
        return objects

    def get_response(self, request) -> requests.Response:
        user = request.user if request.user.is_authenticated else None
        response = Request(query=self, user=user).get()
        self.url = response.url
        self.save()
        return response

    def get_results(self, request, get_from_cache=False):
        """ Get results. Use the session cache to store them for quick access later."""
        key = f'query_{self.id}_results'
        if get_from_cache and (key in request.session):
            results = request.session[key]
        else:
            results = Results(self, self.get_response(request))
            request.session[key] = results
        return results


class QueryFilter(models.Model):
    """
    Represents a single filter attached to the query. Links the query with a filter
    from the parameters and defines the filter value.
    """
    query = models.ForeignKey(
        Query,
        on_delete=models.CASCADE,
        related_name='filters',
        related_query_name='filter',
    )
    on_attribute = models.ForeignKey(
        MbtaFilter,
        on_delete=models.CASCADE,
        related_name='query_instances',
        related_query_name='query_instance',
    )
    values = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.on_attribute} = {self.values}'


class Request(models.Model):
    """
    Created any time a user wants to get/view the results of a given query.
    Handles building the request URL, headers, and parameters, as well as
    sending the request to the MBTA API and receiving the response.

    The user, datetime, and response status code are logged. This also handles
    updating the 'url' field on the Query.
    """

    query = models.ForeignKey(
        Query,
        on_delete=models.CASCADE,
        related_name='requests',
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        default=None,
    )
    datetime = models.DateTimeField('date/time', default=timezone.now)
    response_status_code = models.PositiveSmallIntegerField(
        'status code', blank=True, null=True)
    response_size_bytes = models.IntegerField('response size', blank=True, null=True)

    class Meta:
        ordering = ['-datetime']

    def __str__(self):
        return f'{self.query} -> {self.response_status_code}'

    def url(self) -> str:
        return requests.compat.urljoin('https://api-v3.mbta.com', self.query.primary_object.path)

    def headers(self) -> dict:
        return {'X-API-Key': settings.MBTA_API_KEY}

    def params(self) -> OrderedDict:
        params = OrderedDict()
        # Included objects
        if self.query.includes.all().exists():
            params['include'] = ','.join((x.name for x in self.query.includes.all()))
        # Filters
        for f in self.query.filters.all():
            params[f'filter[{f.on_attribute.name}]'] = f.values
        # Fields/attributes (parameter is only added/needed if some attributes will be excluded)
        for o in self.query.all_objects():
            attributes = [a.name for a in self.query.attributes.filter(for_object=o)]
            if len(attributes) < len(o.attributes.all()):
                params[f'fields[{o.name.lower()}]'] = ','.join(attributes)

        return params

    def get(self) -> requests.Response:
        """ Converts a query into a request and then gets the response """
        response = requests.get(self.url(), headers=self.headers(), params=self.params())
        self.datetime = timezone.now()
        self.response_status_code = response.status_code
        self.response_size_bytes = len(response.content)
        self.save()
        return response


class Results:
    """
    This model is not stored in any database.
    It handles converting a query response into useful data.
    Any time a query is invoked, it will use the response from the
    MBTA API to construct a Results object instance.

    The properties and methods are used to construct displays or
    screen components in web pages so that users can interact with
    the results of their queries.
    """

    def __init__(self, query: Query, response: requests.Response):
        self.query = query
        self.response = response
        if response.ok:
            try:
                self.df = create_DataFrame(response)
                reduce_DataFrame_memory_usage(self.df)
                self.error = None
                self.error_details = None
                self.response_size_bytes = len(response.content)
            except AssertionError as error:
                self.df = None
                self.error = error
                self.error_detail = ''
        else:
            self.df = None
            self.error = f'{response.status_code} {response.reason}'
            self.error_details = get_error_details(response)

    @property
    def data_frame(self) -> pd.DataFrame:
        return self.df

    @property
    def data_frame_rows(self):
        class data_frame_cell:
            def __init__(self, row, col, df):
                self.row_id = row
                self.col_id = col
                self.value = df.at[row, col]

        class data_frame_row:
            def __init__(self, row, df):
                self.id = row
                self.cells = [data_frame_cell(row, col, df)
                              for col in df.columns]

        return [data_frame_row(row, self.df) for row in self.df.index]

    @property
    def pretty_json(self) -> str:
        return json.dumps(self.response.json(), sort_keys=True, indent=2)

    @property
    def column_dtypes(self) -> dict:
        return {col: self.df[col].dtype.name for col in self.df.columns}

    def generate_report_html(self, correlations=None) -> str:
        """ Produce a report using the pandas-profiling module """
        df = self.df.applymap(lambda v: tuple(v) if type(v) == list else v)
        correlations = [] if correlations is None else correlations
        corr_options = ['pearson', 'spearman', 'kendall', 'phi_k', 'cramers', 'recoded']
        corrs = {k: True if k in correlations else False for k in corr_options}
        return df.profile_report(correlations=corrs).to_html()

    def location_plots(self):
        """ If there are latitude/longitude columns, use them to build bokeh geographical plots.
            The JSON data built here will be consumed by a script in the page and used to embed
            interactive plots."""

        def coord_transform_func(lat_col, lon_col):
            """ creates and returns a function for transforming lat & lon columns into web mercator"""
            latlon_proj = Proj(init='epsg:4326')
            webmercator_proj = Proj(init='epsg:3857')

            def transform_func(data):
                x, y = transform(latlon_proj, webmercator_proj, data[lon_col], data[lat_col])
                return pd.Series({'x': x, 'y': y})

            return transform_func

        lat_columns = [c for c in self.df.columns if c.endswith('latitude')]
        lon_columns = [c for c in self.df.columns if c.endswith('longitude')]
        plots = []

        for lat_col in lat_columns:
            col_pfx = lat_col[:-len('latitude')]
            lon_col = f'{col_pfx}longitude'

            if lon_col in lon_columns:
                coords = self.df.apply(coord_transform_func(lat_col, lon_col), axis=1)
                timestamp = date_format(timezone.localtime(timezone.now()), 'DATETIME_FORMAT')
                object_name = self.query.primary_object.name if not col_pfx else col_pfx.rstrip('_').title()
                title = f'{object_name} locations as of {timestamp}'
                source = ColumnDataSource(data=dict(
                    x=coords.x.tolist(),
                    y=coords.y.tolist(),
                    id=self.df[f'{col_pfx}id'].tolist(),
                    latitude=self.df[lat_col].tolist(),
                    longitude=self.df[lon_col].tolist()
                ))
                hover = HoverTool(tooltips=[
                    ('id', '@id'),
                    ('latitude', '@latitude'),
                    ('longitude', '@longitude')
                ])
                plot = figure(
                    x_range=(coords.x.min(), coords.x.max()),

queries/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple
from .models import Query
from params.models import MbtaObject, MbtaInclude, MbtaAttribute


class QueryForm(forms.ModelForm):
    filters = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Query
        fields = ['primary_object', 'includes', 'attributes']
        widgets = {
            'includes': CheckboxSelectMultiple(),
            'attributes': CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(QueryForm, self).__init__(*args, **kwargs)
        self.fields['primary_object'].queryset = MbtaObject.objects.filter(active=True)
        self.fields['includes'].queryset = MbtaInclude.objects.filter(active=True)
        self.fields['attributes'].queryset = MbtaAttribute.objects.filter(active=True)

queries/views.py
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.db import transaction
from .forms import QueryForm
from .models import Query, QueryFilter, Request
from params.models import MbtaFilter
import json
import logging
import dtale


class QueryCreate(generic.CreateView):
    form_class = QueryForm
    template_name = 'queries/create.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        """ Send out API endpoints for the parameters so javascript can make
            asynchronous requests to refine what options are available """
        context = super().get_context_data(**kwargs)
        context['endpoints'] = {
            'params': {
                'objects': reverse('params:objects'),
            }
        }
        return context

    def form_valid(self, form):
        with transaction.atomic():
            filters = json.loads(form.cleaned_data['filters'])
            self.object = form.save()
            for id_, values in filters.items():
                a = MbtaFilter.objects.get(pk=id_)
                QueryFilter.objects.create(
                    query=self.object, on_attribute=a, values=','.join(values))
        return super(QueryCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('queries:results', kwargs={'pk': self.object.pk})


class RequestList(generic.ListView):
    """ Simple enough, shows recent requests (i.e. query invocations) in
        descending order by datetime. Groups of 5 per page."""
    model = Request
    ordering = ['-datetime']
    template_name = 'queries/request_list.html'
    paginate_by = 5


class QueryResults(generic.DetailView):
    """ The 'Results' model (which is memory-only) actually drives the majority
        of what is seen in this view. It gets set up as part of get_context_data."""
    model = Query
    template_name = 'queries/results.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['results'] = context['query'].get_results(self.request)
        context['report_correlations'] = ['pearson', 'spearman', 'kendall', 'phi_k', 'cramers', 'recoded']
        return context


def results_as_csv(request, pk):
    """
    For a given query, this will convert the pandas dataframe of results into
    a CSV file and download it onto the user's device.
    """
    query = get_object_or_404(Query, pk=pk)
    results = query.get_results(request, get_from_cache=True)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="mbta_api_query_{query.pk}.csv"'
    results.df.to_csv(path_or_buf=response, index=False)
    return response


def results_create_report(request, pk, correlations):
    """ Generates a pandas profiling report. Spits back the HTML for the entire doc.
        Unfortunately this includes all the bootstrap stuff, so it's huge.
        Gotta embed it in an iframe """
    query = get_object_or_404(Query, pk=pk)
    results = query.get_results(request, get_from_cache=True)
    correlations = None if correlations == 'NONE' else correlations.split(',')
    try:
        report = results.generate_report_html(correlations=correlations)
        return HttpResponse(report)
    except Exception as e:
        logging.exception(f'Error creating profile report: {e}')
        return HttpResponse(status=500)


def results_dtale(request, pk):
    """Start up a D-Tale process for the current dataframe and attempt to redirect
       the user to it."""
    query = get_object_or_404(Query, pk=pk)
    results = query.get_results(request, get_from_cache=True)
    # TODO:
    #   check if a dtale process for this dataframe already exists...
    #   manage the number of d-tale processes running...etc.
    return redirect(dtale.show(results.df, name=pk)._url)

queries/templates/queries/create.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extrastyles %}
  <link rel="stylesheet" type="text/css" href="{% static 'queries/css/create.css' %}">
{% endblock extrastyles %}

{% block content %}
  {% include "core/modal.html" %}
  {% include "core/loading_screen.html" %}
  <div class="container">
    <h3 class="bd-title py-md-3">Create a query</h3>
    <p>Select the objects and attributes you'd like to have returned, as well as any filters to refine the results.</p>
    <hr>
    <form action="" method="post">{% csrf_token %}
      <div class="form-group{% if form.primary_object.errors %} invalid{% endif %}">
        {{ form.primary_object.label_tag }}
        {% render_field form.primary_object class+="form-control" %}
        {% for error in form.primary_object.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
      <hr>
      <div class="form-group{% if form.includes.errors %} invalid{% endif %}">
        {{ form.includes.label_tag }}
        {{ form.includes }}
        {% for error in form.includes.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
      <hr>
      <div class="form-group{% if form.attributes.errors %} invalid{% endif %}">
        {{ form.attributes.label_tag }}
        {{ form.attributes }}
        {% for error in form.attributes.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
      <hr>
      {{ form.filters }}
      <div class="form-group {% if form.filters.errors %} invalid{% endif %}">
        <label for="filters_list">Filters</label>
        <div class="form-group" id="filters_list"></div>
        {% for error in form.filters.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
      <hr>
      <button type="submit" class="save btn btn-primary btn-lg" id="get_results_btn">Get Results</button>
    </form>
  </div>
{% endblock content %}

{% block extrascripts %}
  {{ endpoints|json_script:"endpoints" }}
  <script type="module" src="{% static 'queries/js/create/main.js' %}"></script>
{% endblock extrascripts %}

queries/templates/queries/request_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load pagination_extras %}

{% block extrastyles %}
  <link rel="stylesheet" type="text/css" href="{% static 'queries/css/request_list.css' %}">
{% endblock extrastyles %}


{% block content %}
  {% include "core/loading_screen.html" %}
  <div class="container">
    <h3 class="bd-title py-md-3">Recent requests</h3>
    <ul class="list-group list-group-flush">
      {% for request in object_list %}
        {% with query=request.query %}
    		  <li class="list-group-item">
            <dl class="row">
              <dt class="col-sm-3">Date/time</dt>
    				  <dd class="col-sm-9">{{ request.datetime }}</dd>
    				  <dt class="col-sm-3">Response status code</dt>
    				  <dd class="col-sm-9">{{ request.response_status_code }}</dd>
    				  <dt class="col-sm-3">Response size</dt>
    				  <dd class="col-sm-9">{{ request.response_size_bytes|filesizeformat }}</dd>
    				  <dt class="col-sm-3">URL</dt>
    				  <dd class="col-sm-9">{{ query.url|urlizetrunc:100 }}</dd>
              <dt class="col-sm-3">Primary Object</dt>
              <dd class="col-sm-9">{{ query.primary_object }}</dd>
            </dl>
            <a class="btn btn-secondary btn-sm" href="{% url 'queries:results' query.pk %}" role="button" id="view_results_{{ query.pk }}">View results</a>
    		  </li>
        {% endwith %}
      {% empty %}
        <li>No queries yet.</li>
      {% endfor %}
    </ul>
    <nav aria-label="...">
      <ul class="pagination justify-content-center py-3">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1" aria-label="First"><span aria-hidden="true">&laquo;</span></a></li>
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">&lsaquo;</a></li>
  		  {% else %}
          <li class="page-item disabled"><span class="page-link" aria-label="First"><span aria-hidden="true">&laquo;</span></span></li>
          <li class="page-item disabled"><span class="page-link" aria-label="Previous"><span aria-hidden="true">&lsaquo;</span></span></li>
  		  {% endif %}
  		  {% visible_page_nums paginator page_obj as page_nums %}
  		  {% for i in page_nums %}
          {% if page_obj.number == i %}
            <li class="page-item active" aria-current="page">
              <span class="page-link">{{ i }}<span class="sr-only">(current)</span></span>
  				  </li>
          {% else %}
  				  <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
  		  {% endfor %}
  		  {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&rsaquo;</span></a></li>
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last"><span aria-hidden="true">&raquo;</span></a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link" aria-label="Next"><span aria-hidden="true">&rsaquo;</span></span></li>
          <li class="page-item disabled"><span class="page-link" aria-label="Last"><span aria-hidden="true">&raquo;</span></span></li>
  		  {% endif %}
      </ul>
    </nav>
  </div>
{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript">
    Array.from(document.querySelectorAll('a[id^="view_results"]')).forEach(link => {
      link.onclick = (event) => {
        document.getElementById('loading-screen-message').innerText = 'Retrieving data...';
        $('#modal-loading-screen').modal('show');
      }
    });
  </script>
{% endblock extrascripts %}

queries/templates/queries/results.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extrastyles %}
  <link rel="stylesheet" type="text/css" href="{% static 'queries/css/results.css' %}">
{% endblock extrastyles %}

{% block content %}
  {% include "core/modal.html" %}
  {% include "core/loading_screen.html" %}

  {% if results.error %}
    <p>Error: {{ results.error }}</p>
    <p>{{ results.error_detail }}</p>
  
  {% elif results.data_frame.empty %}
    <p>No data</p>

  {% else %}
    <!-- tabs -->
    <ul class="nav nav-tabs" id="resultTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#summary" id="id_tab_summary" role="tab" aria-controls="summary" aria-selected="true">Summary</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#full-table" id="id_tab_table" role="tab" aria-controls="full-table" aria-selected="false">Table</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#report" id="id_tab_report" role="tab" aria-controls="report" aria-selected="false">Report</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#raw-data" id="id_tab_raw_data" role="tab" aria-controls="raw-data" aria-selected="false">JSON</a>
      </li>
      {% if not results.location_plots|length_is:"0" %}
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#locations" id="id_tab_locations" role="tab" aria-controls="locations" aria-selected="false">Locations</a>
        </li>
      {% endif %}
    </ul>
    <!-- tab panes -->
    <div class="tab-content my-3">
      <!-- summary -->
      <div class="tab-pane active p-3" id="summary" role="tabpanel" aria-labelledby="id_tab_summary">
        <dl class="row">
          <dt class="col-sm-3">URL</dt>
          <dd class="col-sm-9">{{ results.response.url|urlizetrunc:100 }}</dd>
          <dt class="col-sm-3">Response size</dt>
          <dd class="col-sm-9">{{ results.response_size_bytes|filesizeformat }}</dd>
          <dt class="col-sm-3">Primary Object</dt>
          <dd class="col-sm-9">{{ query.primary_object }}</dd>
          <dt class="col-sm-3">Includes</dt>
          <dd class="col-sm-9">
            {% if query.includes.all.count > 0 %}
              {{ query.includes.all|join:", " }}
            {% else %}
              None
            {% endif %}
          </dd>
          <dt class="col-sm-3">Attributes</dt>
          <dd class="col-sm-9">{{ query.attributes.all|join:", " }}</dd>
          <dt class="col-sm-3">Filters</dt>
          <dd class="col-sm-9">
            {% if query.filters.all.count > 0 %}
              {{ query.filters.all|join:", " }}
            {% else %}
              None
            {% endif %}
          </dd>
        </dl>
        <a href="{% url 'queries:results-dtale' query.pk %}" target="_blank" class="btn btn-primary" role="button">View results in D-Tale</a>
      </div>
      <!-- full table -->
      <div class="tab-pane" id="full-table" role="tabpanel" aria-labelledby="id_tab_table">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
              <a href="{% url 'queries:results-csv' query.pk %}" class="btn btn-sm btn-secondary" role="button">Export to CSV</a>
            </div>
            <button type="button" class="btn btn-sm btn-secondary" id="edit_columns_button">Edit columns displayed</button>
          </div>
        </div>
        <div class="flex-grow-1">
          <div class="table-responsive" style="max-height:66vh;overflow-y:auto;">
            <table class="table table-sm table-striped">
              <thead class="thead-light">
                <tr>
                  {% for col in results.df.columns %}
                    <th scope="col" id="{{ col }}" class="sticky-top p-2">{{ col }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for row in results.data_frame_rows %}
                  <tr id="{{ row.id }}">
                    {% for cell in row.cells %}
                      <td id="{{ cell.row_id }}|{{ cell.col_id }}">{{ cell.value }}</td>
                    {% endfor %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- report -->
      <div class="tab-pane" id="report" role="tabpanel" aria-labelledby="id_tab_report">
        <!-- form for specifying parameters -->
        <div class="p-3" id="report_form_container">
          <form action="" id="report_form" data-endpoint="{% url 'queries:results' pk=query.pk %}report/">
            <div class="form-group">
              <div class="alert alert-warning" role="alert">
                Calculating correlations significantly increases the time required to generate a report.
              </div>
              <label for="id_report_correlations">Correlations</label>
              <ul id="id_report_correlations" class="form-checkbox-list">
                {% for correlation in report_correlations %}
                  <li>
                    <label for="id_report_correlations_{{ correlation }}">
                      <input type="checkbox" value="{{ correlation }}" id="id_report_correlations_{{ correlation }}">
                      {{ correlation }}
                    </label>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <button type="submit" class="save btn btn-primary" id="report_form_submit_btn">Generate report</button>
          </form>
        </div>
        <div id="report-container"><!-- javascript will embed iframe --></div>
      </div>
      <!-- raw data -->
      <div class="tab-pane p-3" id="raw-data" role="tabpanel" aria-labelledby="id_tab_raw_data">
        <pre>{{ results.pretty_json }}</pre>
      </div>
      <!-- locations -->
      <div class="tab-pane" id="locations" role="tabpanel" aria-labelledby="id_tab_locations">
        <div class="pr-3">
          <div id="id_location_plots"><!-- bokeh will embed them --></div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content %}

{% block extrascripts %}
  {% if not results.error %}
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.js"></script>
    {{ results.location_plots|json_script:"location_plots" }}
    <script type="module" src="{% static 'queries/js/results/table.js' %}"></script>
    <script type="module" src="{% static 'queries/js/results/report.js' %}"></script>
    <script type="module" src="{% static 'queries/js/results/locations.js' %}"></script>
  {% endif %}
{% endblock extrascripts %}